---
- hosts: dev
  user: ansible
  become: true
  tasks:
    - name: Install Maven using Ansible
      become: yes
      ansible build:
        - name: "{{ packages }}"
        state: present
      vars:
        packages:
           - maven
